###

GET http://localhost:8080/v1/movies
Content-Type: application/json

###
GET http://localhost:8080/v1/movies/id=1
Content-Type: application/json

###
GET http://localhost:8080/v1/movies/t=matrix
Content-Type: application/json

###
GET http://localhost:8080/v1/movies/count
Content-Type: application/json

###
POST http://localhost:8080/v1/movies
Content-Type: application/json

{
    "title": "Terminator",
    "year": 1984
}

###
PUT http://localhost:8080/v1/movies/id=4
Content-Type: application/json

{
    "title": "Updated",
    "year": 1984
}
